import React from 'react'
import type { Metadata } from 'next'
import '@/styles/global.css'
import { Roboto } from 'next/font/google'
import { ProviderGymContext } from '@/contexts/GymContext'

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['100', '300', '400', '500', '700', '900'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <ProviderGymContext>{children}</ProviderGymContext>
      </body>
    </html>
  )
}
